name: Main Edge Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn
        
      - name: Install Azion CLI
        run: |
          curl -o azionlinux https://downloads.azion.com/linux/x86_64/azion
          sudo mv azionlinux /usr/bin/azion
          sudo chmod u+x /usr/bin/azion

      - name: Create .env file
        run: |
          echo "COSMIC_BUCKET_SLUG=${{ secrets.COSMIC_BUCKET_SLUG }}" >> .env
          echo "COSMIC_READ_KEY=${{ secrets.COSMIC_READ_KEY }}" >> .env
          echo "COSMIC_WRITE_KEY=${{ secrets.COSMIC_WRITE_KEY }}" >> .env
          echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env

      - name: Azion Action Deploy
        run: |
          azion -t ${{ secrets.AZION_PERSONAL_TOKEN }}
          azion deploy
